### ISSUE TITLE
Deploy: Make user download index.html as .zip folder

### ISSUE THREAD

**Issue by Adedoyin-Emmanuel** [chriskthomas/linkfree-generator#21]
We can add an option to make the user download the index.html file as a zipped file so they can easily deploy it on Netlify

![Screenshot from 2023-07-30 17-57-40](https://github.com/chriskthomas/linkfree-generator/assets/88517758/36e53a52-8f78-4041-a31b-74c78078ceee)
 pages.

**Comment by chriskthomas** [comment]
Good idea. This is possible with output buffers and the ziparchive library in php:

* https://www.php.net/manual/en/book.outcontrol.php
* https://www.php.net/manual/en/ziparchive.addfromstring.php
* https://www.php.net/manual/en/function.tmpfile.php

As an alternative to ziparchive and tmpfile, I could use [ZipStream](https://github.com/maennchen/ZipStream-PHP). However, that would complicate the project somewhat.

This is probably something that I should do, but if someone thinks that they can do it, I'm happy to assign.

**Comment by Adedoyin-Emmanuel** [comment]
@chriskthomas can you assign the task to me

**Comment by chriskthomas** [comment]
> @chriskthomas can you assign the task to me

Sure! I think you'll want to:

 - Refactor the code in `api.php` so that it always writes to an output buffer
 - Add a checkbox to the interface in `index.php` for zipping the file
 - When `api.php` sees that the checkbox is false: print the output buffer and exit
 - When `api.php` sees that the checkbox is true: (1) create a tempfile zip archive, (2) add the output buffer as a string to the archive, and (3) send the archive as a download

**Comment by chriskthomas** [comment]
@Adedoyin-Emmanuel are you still interested in doing this? Let me know if you need any help.
